name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test with Maven
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd commerce_backend
          mvn clean test  # Run unit tests
          mvn clean package  # Package the application

      - name: Docker Build and Push
        env:
          AZURE_CR_USERNAME: ${{ secrets.AZURE_CR_USERNAME }}
          AZURE_CR_PASSWORD: ${{ secrets.AZURE_CR_PASSWORD }}
        run: |
          cd commerce_backend
          docker login commerceregistry.azurecr.io -u $AZURE_CR_USERNAME -p $AZURE_CR_PASSWORD
          docker build -t commerceregistry.azurecr.io/ecommerce-backend:latest .
          docker push commerceregistry.azurecr.io/ecommerce-backend:latest

